runtime: python311
entrypoint: gunicorn -b :$PORT app:app
instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1

env_variables:
  SECRET_KEY: "loukas10"

runtime_config:
  python_version: 3
